"""attempt

Revision ID: 2aba7961b424
Revises: c7660262ac1e
Create Date: 2024-12-10 12:34:24.295870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aba7961b424'
down_revision = 'c7660262ac1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('site_primary_contact', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('site_code', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'site', ['site_code'])
    op.create_unique_constraint(None, 'site', ['site_primary_contact'])
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_column('site', 'site_code')
    op.drop_column('site', 'site_primary_contact')
    # ### end Alembic commands ###
