"""remove db table and add foreign key

Revision ID: 3818341fdf21
Revises: 2aba7961b424
Create Date: 2025-01-03 12:47:48.668275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3818341fdf21'
down_revision = '2aba7961b424'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pack_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_id',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pack_ids', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_ids')
    )
    # ### end Alembic commands ###
