"""remove unique constraint from name

Revision ID: 39827e36cddd
Revises: 92b582406202
Create Date: 2024-11-18 09:59:12.483780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39827e36cddd'
down_revision = '92b582406202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
