"""adding new relationship to packshipment table

Revision ID: 59beea3b68fb
Revises: 
Create Date: 2025-01-13 14:07:36.103130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59beea3b68fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
