"""generate new tables

Revision ID: 69f55e163cdb
Revises: 6dc68b8441a4
Create Date: 2024-12-06 15:50:23.116951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, Integer


# revision identifiers, used by Alembic.
revision = '69f55e163cdb'
down_revision = '6dc68b8441a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site") as batch_op:
        batch_op.add_column(mapped_column('back_up_contact', String(100), nullable=False, unique=True))
        batch_op.add_column(mapped_column('site_primary_contact', String(100), nullable=False, unique=True))
        batch_op.add_column(mapped_column('site_code', String(100), nullable=False, unique=True))
       
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    # ### end Alembic commands ###
