"""generate new tables

Revision ID: 6dc68b8441a4
Revises: af2606a53437
Create Date: 2024-12-06 15:16:36.003653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column



# revision identifiers, used by Alembic.
revision = '6dc68b8441a4'
down_revision = 'af2606a53437'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("some_table") as batch_op:
        batch_op.add_column(Mapped('back_up_contact', str))
        batch_op.add_column(Mapped('site_primary_contact', str))
        batch_op.add_column(Mapped('site_code', str))
       


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    # ### end Alembic commands ###
