"""update name def in packs

Revision ID: 72b900a09757
Revises: c98cbf12444d
Create Date: 2026-06-08 12:17:32.837782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b900a09757'
down_revision = 'c98cbf12444d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
