"""add consumables

Revision ID: 77e6e2ef24c2
Revises: 0133effdf060
Create Date: 2024-11-14 10:54:21.869526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e6e2ef24c2'
down_revision = '0133effdf060'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumables',
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('consumable_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumables')
    # ### end Alembic commands ###
