"""create packs

Revision ID: 92b582406202
Revises: e6ed65f8faa4
Create Date: 2024-11-14 11:30:43.403306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b582406202'
down_revision = 'e6ed65f8faa4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packs_pack_id'), 'packs', ['pack_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packs_pack_id'), table_name='packs')
    op.drop_table('packs')
    # ### end Alembic commands ###
