"""generate new tables

Revision ID: a7e5b9937d9b
Revises: c3c4d6bd6ccd
Create Date: 2024-12-06 14:42:48.951819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e5b9937d9b'
down_revision = 'c3c4d6bd6ccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_ids', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_ids')
    )
    op.create_table('pack_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pack_ids', sa.Integer(), nullable=False),
    sa.Column('pack_expiry', sa.Date(), nullable=False),
    sa.Column('addressee', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.Date(), nullable=False),
    sa.Column('date_recieved', sa.Date(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_ids')
    )
    op.alter_column('pack_types', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('site', sa.Column('back_up_contact', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('site_primary_contact', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('site_code', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'site', ['site_code'])
    op.create_unique_constraint(None, 'site', ['back_up_contact'])
    op.create_unique_constraint(None, 'site', ['site_primary_contact'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_column('site', 'site_code')
    op.drop_column('site', 'site_primary_contact')
    op.drop_column('site', 'back_up_contact')
    op.alter_column('pack_types', 'name',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('pack_shipments')
    op.drop_table('pack_id')
    # ### end Alembic commands ###
