"""generate new tables

Revision ID: af2606a53437
Revises: a7e5b9937d9b
Create Date: 2024-12-06 14:46:55.265141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2606a53437'
down_revision = 'a7e5b9937d9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site', sa.Column('back_up_contact', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('site_primary_contact', sa.String(length=100), nullable=False))
    op.add_column('site', sa.Column('site_code', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'site', ['site_code'])
    op.create_unique_constraint(None, 'site', ['site_primary_contact'])
    op.create_unique_constraint(None, 'site', ['back_up_contact'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_constraint(None, 'site', type_='unique')
    op.drop_column('site', 'site_code')
    op.drop_column('site', 'site_primary_contact')
    op.drop_column('site', 'back_up_contact')
    # ### end Alembic commands ###
