"""attempt to add foreign key

Revision ID: af67bda1ee26
Revises: 02b728a70a8a
Create Date: 2025-01-07 12:26:09.331140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af67bda1ee26'
down_revision = '02b728a70a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack_types', sa.Column('packs_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pack_types', 'packs', ['packs_id'], ['id'])
    op.add_column('packs', sa.Column('pack_identity', sa.Integer(), nullable=False))
    op.drop_index('ix_packs_pack_id', table_name='packs')
    op.create_index(op.f('ix_packs_pack_identity'), 'packs', ['pack_identity'], unique=False)
    op.drop_column('packs', 'pack_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packs', sa.Column('pack_id', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_packs_pack_identity'), table_name='packs')
    op.create_index('ix_packs_pack_id', 'packs', ['pack_id'], unique=False)
    op.drop_column('packs', 'pack_identity')
    op.drop_constraint(None, 'pack_types', type_='foreignkey')
    op.drop_column('pack_types', 'packs_id')
    # ### end Alembic commands ###
