"""add  unique constraint from name

Revision ID: b367b136c63c
Revises: 39827e36cddd
Create Date: 2024-11-18 10:17:59.339710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b367b136c63c'
down_revision = '39827e36cddd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
