"""update name def in packs

Revision ID: bc2a8c2fcf3e
Revises: 72b900a09757
Create Date: 2026-06-08 12:22:24.347494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2a8c2fcf3e'
down_revision = '72b900a09757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
