"""remove next due date received from ps tables

Revision ID: c16cccc311e4
Revises: bc2a8c2fcf3e
Create Date: 2026-06-09 09:16:10.949412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16cccc311e4'
down_revision = 'bc2a8c2fcf3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pack_shipment', 'date_received')
    op.drop_column('pack_shipment', 'next_due')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pack_shipment', sa.Column('next_due', sa.DATE(), nullable=True))
    op.add_column('pack_shipment', sa.Column('date_received', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
