"""new table attempt 2

Revision ID: c3c4d6bd6ccd
Revises: 7d5709e33f2f
Create Date: 2024-11-20 10:14:28.567966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c4d6bd6ccd'
down_revision = '7d5709e33f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
