"""add new column

Revision ID: c7660262ac1e
Revises: 966790f0eae2
Create Date: 2024-12-09 16:21:41.174491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7660262ac1e'
down_revision = '966790f0eae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
